parameters:
#    gestion_pass.example.class: Gestion\PassBundle\Example

services:
#    gestion_pass.example:
#        class: %gestion_pass.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
