<?php

namespace Gestion\PassBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CameraRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CameraRangeRepository extends EntityRepository
{
}
