<?php

namespace Gestion\PassBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CameraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CameraRepository extends EntityRepository
{
}
