<?php

namespace Gestion\PassBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConsigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsigneRepository extends EntityRepository
{
    
        public function nbrConsigne(){
            $em=$this->getEntityManager();
            $qb = $em->createQueryBuilder('cons');
            $qb->select('count(cons.id)')        //            $qb->select('count(a.id)')
                   ->from('GestionPassBundle:Consigne', 'cons');
            $query=$qb->getQuery();
           $result= $query->getSingleScalarResult();

            return  $result  ;
        }      
}
