<?php

namespace Gestion\PassBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;

/**
 * FacilitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilitationRepository extends EntityRepository
{
    
        public function nbrFacilitationEncours(){
    
            $em=$this->getEntityManager();

            $qb = $em->createQueryBuilder('fa');
        $qb->select('count(fa.id)')        //            $qb->select('count(a.id)')
               ->from('GestionPassBundle:Facilitation', 'fa')
                ->where('fa.dateReglement IS NULL') ;
        $query=$qb->getQuery();
        $result= $query->getSingleScalarResult();
//         $response = new Response('' + $result);
        return $result  ;
    
}
}