<?php

namespace Gestion\PassBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;
/**
 * FluiditeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluiditeRepository extends EntityRepository
{
    
        public function nbrFluiditeEncours(){
            $em=$this->getEntityManager();
    
            $qb = $em->createQueryBuilder('f');
        $qb->select('count(f.id)')        //            $qb->select('count(a.id)')
               ->from('GestionPassBundle:Fluidite', 'f')
                ->where('f.dateReglement IS NULL') ;
        $query=$qb->getQuery();
        $result= $query->getSingleScalarResult();
//         $response = new Response('' + $result);
        return $result  ;
    
}
}
