parameters:
#    gestion_user.example.class: Gestion\UserBundle\Example

services:
#    gestion_user.example:
#        class: %gestion_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
